# Generated by Django 6.0.1 on 2026-05-17 01:20

import django.db.models.deletion
import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_location', models.CharField(max_length=255)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_phone', models.CharField(max_length=30)),
                ('seller_address', models.TextField()),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_location', models.CharField(max_length=255)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_phone', models.CharField(max_length=30)),
                ('receiver_address', models.TextField()),
                ('tracking_number', models.CharField(default=shipments.models.generate_tracking_number, editable=False, max_length=50, unique=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('type_shipment', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('package_number', models.IntegerField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('courier', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shipment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('pickup_day', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_time', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('gps', models.CharField(blank=True, max_length=50, null=True)),
                ('arrived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='shipments.shipment')),
            ],
        ),
    ]
